# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-29 13:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewDjangoProjectApp', '0005_auto_20160129_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasks',
            name='task',
            field=models.TextField(null=True),
        ),
    ]
