# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-30 10:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewDjangoProjectApp', '0007_auto_20160129_1336'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasks',
            name='user',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
